[tool.poetry]
name = "unittesting-learning"
version = "0.1.0"
description = ""
authors = ["Mohsin Shah <Mohsin.Shah@gosh.nhs.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
